### PR TITLE
Ethan edits

### PR DESCRIPTION
**Pull request by AutogolazzoJr**
Added a separate font stylesheet

### CODE REVIEW

**Comment by DarinMao** [comment]
Why do you need a font.css? Why can't you just combine font.css and style.css?

**Comment by AutogolazzoJr** [comment]
I'd like a seperate stylesheet for fonts. I'd rather not cram everything
into one sheet, right?

**Comment by DarinMao** [comment]
By fonts do you mean defining fonts for different parts of the website, or importing custom fonts?

**Comment by DarinMao** [comment]
Either way I usually just use one style file. It's fine if you add font.css.

**Comment by AutogolazzoJr** [comment]
Not importing fonts, more like font-family
 {}
stuff like that. It would just easier for multiple people to work on the
site at once.

**Comment by DarinMao** [comment]
Ok I'll merge.

**Comment by AutogolazzoJr** [comment]
Thanks. Looks like you will be more active than Ryan on this.

**Pull request merged**
